name: Deploy page

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy page
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install app dependencies
        run: npm install

      - name: Identify yourself first
        run: git config --global user.email "i.gonzalezl@hotmail.com"

      - name: Identify yourself first
        run: git config --global user.name "nachogl1"

      - name: Deploy
        run: npm run deploy
